### ISSUE TITLE
Backspace not working in CLI

### ISSUE THREAD

**Issue by henrym2** [agurodriguez/bashme#1]
Pressing backspace on Version 70.0.3538.110 (Official Build) (64-bit) is not currently working.

Tested on your personal site @agurodriguez ,

Will build and test locally.

(Awesome interface though by the way! love the project)

**Comment by agurod42** [comment]
Hi @henrym2 👋🏽!

Thank you very much for your feedback. 

Gonna look at this issue. Let you know as soon as possible.

**Comment by agurod42** [comment]
It should be fixed in 0.3.4 version.

Thank you for reporting!
